# TensorBoard
alias tb='tensorboard --bind_all --logdir'
# MatLab
alias mlrun='matlab -nodesktop -nosplash -r'
alias what='ps aux | grep `whoami`'
# command line prompt
PS1="\u@\h \[\033[1;33m\]\w\[\e[0m\]\n\$ "
